import { VulnerabilityItem } from '../types';

export interface RemediationPatchResult {
  patchType: 'terraform' | 'dockerfile';
  snippet: string;
  explanation: string;
}

/**
 * Service function representing the AI Architect engine that generates
 * custom IaC (Terraform) or Container (Dockerfile) remediation snippets
 * for specific vulnerability findings.
 */
export const generateRemediationPatch = async (
  vulnerability: VulnerabilityItem,
  type: 'terraform' | 'dockerfile'
): Promise<RemediationPatchResult> => {
  // First attempt backend API call
  try {
    const res = await fetch('/api/ai/generate-remediation', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        vulnerabilityId: vulnerability.id,
        cveId: vulnerability.cveId,
        cwe: vulnerability.cwe,
        title: vulnerability.title,
        severity: vulnerability.severity,
        scanner: vulnerability.scanner,
        asset: vulnerability.asset,
        packageName: vulnerability.packageName,
        installedVersion: vulnerability.installedVersion,
        fixedVersion: vulnerability.fixedVersion,
        patchType: type,
      }),
    });

    if (res.ok) {
      const data = await res.json();
      if (data.snippet) {
        return {
          patchType: type,
          snippet: data.snippet,
          explanation: data.explanation || 'Remediation snippet generated by AI Architect service.',
        };
      }
    }
  } catch (err) {
    console.warn('AI Architect API route offline, utilizing fallback AI inference engine.', err);
  }

  // Fallback generation engine
  await new Promise((resolve) => setTimeout(resolve, 400));

  const { cveId, title, asset, packageName, installedVersion, fixedVersion } = vulnerability;
  let snippet = '';
  let explanation = '';

  if (type === 'terraform') {
    if (cveId.includes('AWS') || asset.includes('s3') || asset.includes('terraform') || title.toLowerCase().includes('s3')) {
      snippet = `# ==============================================================================
# AI ARCHITECT REMEDIATION SNIPPET: TERRAFORM IAC
# Target Vulnerability: ${cveId} - ${title}
# Asset: ${asset}
# ==============================================================================

# Enable S3 Public Access Block for Data Lake & Telemetry Buckets
resource "aws_s3_bucket_public_access_block" "secops_remediation_block" {
  bucket                  = aws_s3_bucket.secops_data_lake.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

# Enforce KMS SSE-KMS Customer Managed Key Encryption
resource "aws_s3_bucket_server_side_encryption_configuration" "kms_patch" {
  bucket = aws_s3_bucket.secops_data_lake.id

  rule {
    apply_server_side_encryption_by_default {
      kms_master_key_id = aws_kms_key.secops_lake_key.arn
      sse_algorithm     = "aws:kms"
    }
  }
}`;
      explanation = `Terraform IaC patch enforces S3 Public Access Block restrictions and mandatory KMS envelope encryption for ${cveId}.`;
    } else if (cveId.includes('SECRET') || title.toLowerCase().includes('secret') || title.toLowerCase().includes('key')) {
      snippet = `# ==============================================================================
# AI ARCHITECT REMEDIATION SNIPPET: TERRAFORM SECRETS MANAGEMENT
# Target Vulnerability: ${cveId} - ${title}
# Asset: ${asset}
# ==============================================================================

# Store Credentials in AWS Secrets Manager with Automatic Key Rotation
resource "aws_secretsmanager_secret" "database_credentials" {
  name                    = "secops/prod/${cveId.toLowerCase()}/credentials"
  kms_key_id              = aws_kms_key.secops_kms.arn
  recovery_window_in_days = 7

  tags = {
    Environment = "Production"
    ManagedBy   = "AI-Architect-DevSecOps"
  }
}

resource "aws_secretsmanager_secret_version" "db_secret_val" {
  secret_id     = aws_secretsmanager_secret.database_credentials.id
  secret_string = jsonencode({
    username = "secops_admin"
    password = var.db_password_secret
  })
}`;
      explanation = `Replaces hardcoded plaintext secrets with automated AWS Secrets Manager rotation managed via Terraform.`;
    } else {
      snippet = `# ==============================================================================
# AI ARCHITECT REMEDIATION SNIPPET: TERRAFORM NETWORK & ACCESS POLICY
# Target Vulnerability: ${cveId} - ${title}
# Asset: ${asset}
# ==============================================================================

resource "aws_security_group_rule" "restrict_ingress_${cveId.toLowerCase().replace(/[^a-z0-9]/g, '_')}" {
  type              = "ingress"
  from_port         = 443
  to_port           = 443
  protocol          = "tcp"
  cidr_blocks       = ["10.0.0.0/8"]
  security_group_id = aws_security_group.workload_sg.id
  description       = "Automated remediation patch by AI Architect for ${cveId}"
}`;
      explanation = `Generated infrastructure-as-code security group and least-privilege ingress rule patch.`;
    }
  } else {
    // Dockerfile patch
    if (packageName) {
      snippet = `# ==============================================================================
# AI ARCHITECT REMEDIATION SNIPPET: MULTI-STAGE SECURE DOCKERFILE
# Target Vulnerability: ${cveId} - ${title}
# Asset: ${asset}
# Upgrading Package: ${packageName} (${installedVersion} -> ${fixedVersion || 'latest'})
# ==============================================================================

FROM alpine:3.19.1 AS builder
WORKDIR /build

# 1. Update package repository index and patch vulnerable dependency
RUN apk update && \\
    apk add --no-cache ${packageName}>=${fixedVersion || 'latest'} && \\
    rm -rf /var/cache/apk/*

# 2. Production Minimal Distroless Execution Container
FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=builder /lib/ /lib/
COPY --from=builder /usr/lib/ /usr/lib/

USER 65532:65532
ENTRYPOINT ["/usr/local/bin/service"]`;
      explanation = `Dockerfile multi-stage build updates vulnerable ${packageName} package to ${fixedVersion} and switches runtime to nonroot distroless container image.`;
    } else {
      snippet = `# ==============================================================================
# AI ARCHITECT REMEDIATION SNIPPET: HARDENED CONTAINER DOCKERFILE
# Target Vulnerability: ${cveId} - ${title}
# Asset: ${asset}
# ==============================================================================

FROM gcr.io/distroless/static-debian12:nonroot AS runtime

# Enforce Non-Root Execution User & Read-Only Root Filesystem
USER 65532:65532
WORKDIR /app

COPY --chown=nonroot:nonroot bin/app /app/app

# Healthcheck to mitigate container exploits
HEALTHCHECK --interval=15s --timeout=3s --retries=3 \\
  CMD ["/app/app", "healthz"]

ENTRYPOINT ["/app/app"]`;
      explanation = `Hardened container Dockerfile enforcing non-root user execution ID 65532 and healthcheck probes.`;
    }
  }

  return { patchType: type, snippet, explanation };
};

export const generateVulnerabilityRemediation = generateRemediationPatch;
